/**
 * Diabetic-Friendly Nigerian Food App — Meal Data
 *
 * All foods are low glycemic index (GI ≤ 55), sourced from African/Nigerian
 * stores in the United States. No starchy foods or sweeteners.
 *
 * Includes breakfast, lunch, and dinner pools plus diabetic-friendly drinks
 * for a 180-day rotating meal plan.
 */

'use strict';

// ─────────────────────────────────────────────
//  BREAKFAST POOL  (30 options, GI ≤ 55)
// ─────────────────────────────────────────────
const BREAKFASTS = [
  {
    id: 'B01',
    name: 'Moimoi with Ugwu Vegetable Sauce',
    gi: 30,
    description: 'Steamed black-eyed pea pudding served with sautéed fluted pumpkin leaf sauce.',
    ingredients: [
      'Black-eyed peas (dried, from African store)',
      'Fluted pumpkin leaves (ugwu)',
      'Fresh tomatoes',
      'Red bell pepper',
      'Scotch bonnet pepper',
      'Onion',
      'Palm oil (1 tsp)',
      'Crayfish (ground)',
      'Salt & ground crayfish to taste',
    ],
    preparation: 'Soak and blend peas, season with pepper, onion, and crayfish, wrap in foil or banana leaves and steam for 40 min. Sauté ugwu with tomatoes and a teaspoon of palm oil.',
    notes: 'High in plant protein and fibre. GI ≈ 30.',
  },
  {
    id: 'B02',
    name: 'Akara (Bean Cakes) with Fresh Pepper Sauce',
    gi: 32,
    description: 'Lightly fried black-eyed pea fritters served with a fresh tomato-scotch bonnet sauce.',
    ingredients: [
      'Black-eyed peas (peeled)',
      'Onion',
      'Scotch bonnet pepper',
      'Fresh tomatoes',
      'Scent leaf (efirin)',
      'Palm oil (for light frying)',
      'Salt to taste',
    ],
    preparation: 'Blend peas with minimal water, add chopped onion and salt. Shallow-fry small balls in palm oil until golden. Blend tomatoes with pepper for raw sauce.',
    notes: 'Use minimal oil. GI ≈ 32.',
  },
  {
    id: 'B03',
    name: 'Scrambled Eggs with Ugwu & Garden Egg',
    gi: 0,
    description: 'Protein-rich eggs scrambled with fluted pumpkin leaves and diced African eggplant.',
    ingredients: [
      'Eggs (3)',
      'Fluted pumpkin leaves (ugwu)',
      'African eggplant (garden egg)',
      'Onion',
      'Scotch bonnet (½)',
      'Coconut oil (1 tsp)',
      'Salt & pepper to taste',
    ],
    preparation: 'Dice garden egg and sauté with onion. Add ugwu and wilt, then pour in beaten eggs and scramble until set.',
    notes: 'Zero GI for eggs. Very filling. GI ≈ 0.',
  },
  {
    id: 'B04',
    name: 'Catfish Pepper Soup',
    gi: 0,
    description: 'Light, aromatic spiced broth with catfish, ginger, and pepper soup spices.',
    ingredients: [
      'Fresh catfish (cut into pieces)',
      'Pepper soup spice mix (ehuru, uziza seeds, utazi)',
      'Ginger (fresh)',
      'Garlic (3 cloves)',
      'Onion',
      'Scent leaf',
      'Scotch bonnet',
      'Salt to taste',
    ],
    preparation: 'Season catfish with ginger, garlic, and salt. Simmer in water with pepper soup spices for 20 min. Add scent leaf at the end.',
    notes: 'Protein- and mineral-rich. GI ≈ 0.',
  },
  {
    id: 'B05',
    name: 'Boiled Eggs & Avocado Garden Egg Salad',
    gi: 10,
    description: 'Hard-boiled eggs with sliced avocado and African eggplant tossed in lemon-herb dressing.',
    ingredients: [
      'Eggs (3, hard-boiled)',
      'Avocado (1, ripe)',
      'African eggplant (garden egg, sliced)',
      'Cucumber',
      'Tomato',
      'Lemon juice',
      'Scent leaf',
      'Salt & black pepper',
    ],
    preparation: 'Combine sliced vegetables and avocado. Halve boiled eggs on top. Drizzle with lemon juice and scatter scent leaf.',
    notes: 'Healthy fats + protein combo. GI ≈ 10.',
  },
  {
    id: 'B06',
    name: 'Vegetable Omelet with Bitter Leaf',
    gi: 0,
    description: 'Fluffy omelet filled with sautéed bitter leaf, tomatoes, and onions.',
    ingredients: [
      'Eggs (3)',
      'Bitter leaf (washed)',
      'Tomato (1, diced)',
      'Onion (½)',
      'Scotch bonnet (½)',
      'Olive oil (1 tsp)',
      'Salt to taste',
    ],
    preparation: 'Sauté onion and tomato, add bitter leaf and wilt. Beat eggs with salt, pour over vegetables, fold into omelet.',
    notes: 'Bitter leaf lowers blood sugar. GI ≈ 0.',
  },
  {
    id: 'B07',
    name: 'Ewa Riro (Nigerian Brown Bean Porridge)',
    gi: 28,
    description: 'Slow-cooked brown beans in a rich tomato-crayfish base — no starchy sides.',
    ingredients: [
      'Brown beans (½ cup)',
      'Tomatoes (2)',
      'Scotch bonnet pepper',
      'Onion',
      'Ground crayfish',
      'Palm oil (1 tsp)',
      'Locust beans (iru)',
      'Salt to taste',
    ],
    preparation: 'Cook beans until soft. Fry tomato-pepper blend in palm oil, add iru and crayfish, combine with beans and simmer 15 min.',
    notes: 'Beans have one of the lowest GI values (~28).',
  },
  {
    id: 'B08',
    name: 'Chicken Pepper Soup (Breakfast Style)',
    gi: 0,
    description: 'Lean chicken pieces in a light herb-spiced broth, great for a warm morning start.',
    ingredients: [
      'Chicken (boneless, skinless)',
      'Pepper soup spices',
      'Ginger',
      'Garlic',
      'Scent leaf',
      'Utazi leaf (small amount)',
      'Onion',
      'Salt to taste',
    ],
    preparation: 'Season chicken with spices and ginger. Simmer until tender (about 30 min). Add scent leaf before serving.',
    notes: 'Lean protein. Very low GI.',
  },
  {
    id: 'B09',
    name: 'Smoked Mackerel & Cucumber Salad',
    gi: 15,
    description: 'Flaked smoked mackerel over crisp cucumber, tomato, and garden egg salad.',
    ingredients: [
      'Smoked mackerel (1 fillet)',
      'Cucumber (½)',
      'Tomatoes (2)',
      'Garden egg (African eggplant, 2)',
      'Onion (½)',
      'Lemon juice',
      'Scent leaf',
      'Black pepper',
    ],
    preparation: 'Flake mackerel. Dice vegetables. Combine everything, squeeze lemon juice, add scent leaf.',
    notes: 'Rich in omega-3 fatty acids. GI ≈ 15.',
  },
  {
    id: 'B10',
    name: 'Sardine Stir-fry with Vegetables',
    gi: 0,
    description: 'Canned sardines stir-fried with okra, onion, and tomato in a quick one-pan meal.',
    ingredients: [
      'Sardines in water (1 can, drained)',
      'Okra (sliced)',
      'Tomatoes (2)',
      'Onion (½)',
      'Scotch bonnet pepper',
      'Scent leaf',
      'Palm oil (1 tsp)',
      'Salt & crayfish',
    ],
    preparation: 'Sauté onion and pepper in palm oil. Add tomatoes, cook down, stir in okra and sardines. Cook 5 min, finish with scent leaf.',
    notes: 'Budget-friendly, calcium-rich. GI ≈ 0.',
  },
  {
    id: 'B11',
    name: 'Egusi Omelet',
    gi: 5,
    description: 'Eggs beaten with ground melon seeds, sautéed onion, and bitter leaf.',
    ingredients: [
      'Eggs (3)',
      'Ground egusi (melon seeds, 2 tbsp)',
      'Bitter leaf (washed)',
      'Onion (½)',
      'Tomato (1)',
      'Scotch bonnet',
      'Coconut oil (1 tsp)',
      'Salt to taste',
    ],
    preparation: 'Mix beaten eggs with egusi, onion, and salt. Pour into heated oil, add bitter leaf and tomato. Cook like an omelet.',
    notes: 'High protein + healthy fats. GI ≈ 5.',
  },
  {
    id: 'B12',
    name: 'Prawn Vegetable Stir-fry',
    gi: 0,
    description: 'Fresh prawns quickly stir-fried with ugwu, tomatoes, and African spices.',
    ingredients: [
      'Prawns (deveined)',
      'Ugwu (fluted pumpkin leaves)',
      'Tomatoes (2)',
      'Onion',
      'Garlic (3 cloves)',
      'Ginger (1 tsp)',
      'Scotch bonnet',
      'Coconut oil (1 tsp)',
      'Salt to taste',
    ],
    preparation: 'Sauté garlic and ginger. Add prawns, cook 3 min. Add tomatoes, pepper, and ugwu. Cook 5 more min.',
    notes: 'Very high protein, almost no GI.',
  },
  {
    id: 'B13',
    name: 'Moimoi with Garden Egg Sauce',
    gi: 30,
    description: 'Steamed bean pudding served with a rich garden egg and tomato sauce.',
    ingredients: [
      'Black-eyed peas',
      'African eggplant (garden egg)',
      'Tomatoes',
      'Scotch bonnet',
      'Onion',
      'Palm oil (1 tsp)',
      'Smoked fish (for sauce)',
      'Crayfish',
      'Salt',
    ],
    preparation: 'Prepare moimoi as usual. Grill garden eggs, blend with tomatoes, fry in palm oil with smoked fish and crayfish.',
    notes: 'GI ≈ 30.',
  },
  {
    id: 'B14',
    name: 'Oha Leaf Egg Scramble',
    gi: 0,
    description: 'Freshly shredded oha leaves scrambled with eggs, onion, and cherry tomatoes.',
    ingredients: [
      'Oha leaves (shredded)',
      'Eggs (3)',
      'Cherry tomatoes (6)',
      'Onion (½)',
      'Scotch bonnet',
      'Olive oil (1 tsp)',
      'Salt & pepper',
    ],
    preparation: 'Sauté onion and tomatoes in oil. Add oha leaf briefly, pour in beaten eggs and scramble.',
    notes: 'Oha is rich in iron and vitamin C. GI ≈ 0.',
  },
  {
    id: 'B15',
    name: 'Tilapia Pepper Soup',
    gi: 0,
    description: 'Whole tilapia in a light, spicy pepper soup broth — a restorative morning meal.',
    ingredients: [
      'Tilapia (1 whole or fillets)',
      'Pepper soup spice blend',
      'Ginger (fresh)',
      'Onion',
      'Scent leaf',
      'Utazi leaf',
      'Scotch bonnet',
      'Salt',
    ],
    preparation: 'Parboil fish 5 min, discard water. Add fresh water, spices, onion, and ginger. Simmer 20 min. Add scent leaf.',
    notes: 'Very light on the digestive system. GI ≈ 0.',
  },
  {
    id: 'B16',
    name: 'Goat Meat Pepper Soup',
    gi: 0,
    description: 'Tender goat meat pieces in a deeply spiced, fragrant pepper soup broth.',
    ingredients: [
      'Goat meat (500g)',
      'Pepper soup spices (ehuru, uziza, uda)',
      'Ginger',
      'Garlic',
      'Onion',
      'Scent leaf',
      'Scotch bonnet',
      'Salt',
    ],
    preparation: 'Pressure-cook goat meat 25 min with onion and salt. Add pepper soup spices and simmer 15 min. Finish with scent leaf.',
    notes: 'Rich in collagen and protein. GI ≈ 0.',
  },
  {
    id: 'B17',
    name: 'Avocado & Smoked Fish Plate',
    gi: 10,
    description: 'Halved avocado stuffed with flaked smoked fish, tomatoes, and herbs.',
    ingredients: [
      'Avocado (1)',
      'Smoked fish (mackerel or titus)',
      'Tomatoes (2)',
      'Onion (½)',
      'Scent leaf',
      'Lemon juice',
      'Black pepper & salt',
    ],
    preparation: 'Halve avocado. Combine flaked smoked fish with diced tomato, onion, and scent leaf. Fill avocado halves. Drizzle lemon.',
    notes: 'Heart-healthy fats. GI ≈ 10.',
  },
  {
    id: 'B18',
    name: 'Cowpea (Bean) Soup with Crayfish',
    gi: 28,
    description: 'Light cowpea soup cooked with crayfish, palm oil, and African spices.',
    ingredients: [
      'Cowpeas (black-eyed peas)',
      'Crayfish (ground)',
      'Locust beans (iru)',
      'Tomatoes',
      'Onion',
      'Scotch bonnet',
      'Palm oil (1 tsp)',
      'Salt',
    ],
    preparation: 'Cook cowpeas until soft. Blend tomatoes, fry in palm oil with iru. Add cooked beans and simmer 10 min.',
    notes: 'GI ≈ 28.',
  },
  {
    id: 'B19',
    name: 'Chicken & Vegetable Soup',
    gi: 0,
    description: 'Clear chicken broth packed with garden egg, ugwu, and aromatic herbs.',
    ingredients: [
      'Chicken (boneless)',
      'Garden egg (sliced)',
      'Ugwu',
      'Ginger',
      'Garlic',
      'Onion',
      'Scent leaf',
      'Salt',
    ],
    preparation: 'Cook chicken with onion and ginger 20 min. Add garden egg and simmer 10 min. Add ugwu and scent leaf; cook 3 min.',
    notes: 'Anti-inflammatory. GI ≈ 0.',
  },
  {
    id: 'B20',
    name: 'Snail Pepper Soup',
    gi: 0,
    description: 'Cleaned garden snail pieces in a fragrant pepper soup broth — a Nigerian delicacy.',
    ingredients: [
      'Garden snails (cleaned)',
      'Pepper soup spices',
      'Ginger',
      'Onion',
      'Scent leaf',
      'Utazi leaf (small amount)',
      'Scotch bonnet',
      'Salt',
    ],
    preparation: 'Parboil snails 10 min. Discard water. Re-cook with spices, ginger, and onion for 25 min. Add scent leaf.',
    notes: 'Very high protein, almost zero fat. GI ≈ 0.',
  },
  {
    id: 'B21',
    name: 'Lentil Soup African Style',
    gi: 32,
    description: 'Red lentils cooked with tomatoes, garlic, turmeric, and African spices.',
    ingredients: [
      'Red lentils (½ cup)',
      'Tomatoes (2)',
      'Garlic (4 cloves)',
      'Ginger (1 tsp)',
      'Turmeric powder (½ tsp)',
      'Scotch bonnet',
      'Onion',
      'Scent leaf',
      'Salt',
    ],
    preparation: 'Boil lentils until soft. Sauté garlic, ginger, and turmeric. Add blended tomatoes and cook down. Combine with lentils.',
    notes: 'Lentils GI ≈ 32. Turmeric aids blood sugar control.',
  },
  {
    id: 'B22',
    name: 'Waterleaf & Egg Stir-fry',
    gi: 0,
    description: 'Tender waterleaf sautéed with eggs, tomatoes, and aromatic spices.',
    ingredients: [
      'Waterleaf (fresh or from African store)',
      'Eggs (3)',
      'Tomatoes (2)',
      'Onion',
      'Scotch bonnet',
      'Coconut oil (1 tsp)',
      'Salt & crayfish',
    ],
    preparation: 'Sauté onion and tomatoes. Add waterleaf; cook until wilted. Push to side, scramble eggs in the same pan, combine.',
    notes: 'High in mucilage (fibre). GI ≈ 0.',
  },
  {
    id: 'B23',
    name: 'Turkey Broth with Vegetables',
    gi: 0,
    description: 'Clear turkey broth with bitter leaf, uziza, and ginger.',
    ingredients: [
      'Turkey (boneless pieces)',
      'Bitter leaf (washed)',
      'Uziza leaves',
      'Ginger',
      'Garlic',
      'Onion',
      'Salt to taste',
    ],
    preparation: 'Cook turkey with onion, ginger, and garlic until tender. Add bitter leaf and uziza; simmer 5 min.',
    notes: 'Lean protein. GI ≈ 0.',
  },
  {
    id: 'B24',
    name: 'Prawn Pepper Soup',
    gi: 0,
    description: 'Juicy prawns in a bold, spiced pepper soup broth with utazi and scent leaf.',
    ingredients: [
      'Prawns (large, deveined)',
      'Pepper soup spice blend',
      'Ginger',
      'Onion',
      'Scent leaf',
      'Utazi leaf',
      'Scotch bonnet',
      'Salt',
    ],
    preparation: 'Season prawns with salt. Bring spiced broth to boil, add prawns and cook 8 min. Add scent leaf.',
    notes: 'Very high protein, minimal GI.',
  },
  {
    id: 'B25',
    name: 'Edikaikong Egg Scramble',
    gi: 0,
    description: 'Classic cross-river mixed greens (edikaikong) scrambled with eggs and crayfish.',
    ingredients: [
      'Fluted pumpkin leaves (ugwu)',
      'Waterleaf',
      'Eggs (3)',
      'Crayfish (ground)',
      'Palm oil (1 tsp)',
      'Onion',
      'Scotch bonnet',
      'Salt',
    ],
    preparation: 'Sauté onion in palm oil. Add vegetables and wilt. Stir in beaten eggs seasoned with crayfish and scramble.',
    notes: 'Iron-rich combination. GI ≈ 0.',
  },
  {
    id: 'B26',
    name: 'Ofe Onugbu (Bitter Leaf Broth)',
    gi: 5,
    description: 'Bitter leaf in a light broth with dried fish and minimal egusi — served as morning soup.',
    ingredients: [
      'Bitter leaf (washed, squeezed)',
      'Dried fish (asa)',
      'Ground egusi (2 tbsp)',
      'Crayfish',
      'Stockfish (soaked)',
      'Onion',
      'Scotch bonnet',
      'Palm oil (1 tsp)',
      'Salt',
    ],
    preparation: 'Fry onion in palm oil, add crayfish and blended egusi. Pour stock, add fish, then bitter leaf. Simmer 15 min.',
    notes: 'Bitter leaf lowers blood sugar. GI ≈ 5.',
  },
  {
    id: 'B27',
    name: 'Catfish Stew with Scent Leaf',
    gi: 0,
    description: 'Tender catfish in a tomato-based stew enriched with scent leaf and African spices.',
    ingredients: [
      'Catfish (pieces)',
      'Tomatoes (3)',
      'Scotch bonnet',
      'Onion',
      'Scent leaf',
      'Garlic',
      'Ginger',
      'Palm oil (1 tsp)',
      'Crayfish',
      'Salt',
    ],
    preparation: 'Blend tomatoes, onion, and pepper. Fry in palm oil with garlic and ginger. Add catfish and simmer 15 min. Add scent leaf.',
    notes: 'Omega-3 rich. GI ≈ 0.',
  },
  {
    id: 'B28',
    name: 'Cow Leg Kanda Pepper Soup',
    gi: 0,
    description: 'Gelatinous cow leg pieces in a traditional pepper soup broth.',
    ingredients: [
      'Cow leg (cleaned and cut)',
      'Pepper soup spices',
      'Ginger',
      'Garlic',
      'Onion',
      'Scent leaf',
      'Scotch bonnet',
      'Salt',
    ],
    preparation: 'Pressure-cook cow leg 45 min. Add pepper soup spices and simmer 20 min more. Finish with scent leaf.',
    notes: 'Collagen-rich. GI ≈ 0.',
  },
  {
    id: 'B29',
    name: 'Chicken Okra Stir-fry',
    gi: 0,
    description: 'Diced chicken stir-fried with whole okra, tomatoes, and locust beans.',
    ingredients: [
      'Chicken (diced)',
      'Okra (small, whole)',
      'Tomatoes (2)',
      'Locust beans (iru)',
      'Onion',
      'Scotch bonnet',
      'Palm oil (1 tsp)',
      'Salt',
    ],
    preparation: 'Stir-fry chicken until cooked. Add onion, tomatoes, and iru. Add whole okra and cook 5 min until just tender.',
    notes: 'Okra fibre slows glucose absorption. GI ≈ 0.',
  },
  {
    id: 'B30',
    name: 'Afang-style Vegetable Omelet',
    gi: 0,
    description: 'Eggs combined with shredded afang (wild spinach) and waterleaf for a rich omelet.',
    ingredients: [
      'Afang leaves (shredded)',
      'Waterleaf',
      'Eggs (3)',
      'Onion',
      'Scotch bonnet',
      'Crayfish (ground)',
      'Palm oil (½ tsp)',
      'Salt',
    ],
    preparation: 'Briefly sauté afang and waterleaf in palm oil with onion. Pour beaten eggs over the top and cook as an omelet.',
    notes: 'Highly nutritious leaf combination. GI ≈ 0.',
  },
];

// ─────────────────────────────────────────────
//  LUNCH POOL  (30 options, GI ≤ 55)
// ─────────────────────────────────────────────
const LUNCHES = [
  {
    id: 'L01',
    name: 'Egusi Soup with Bitter Leaf & Beef',
    gi: 25,
    description: 'Hearty ground melon seed soup with bitter leaf and tender beef — no swallow.',
    ingredients: [
      'Ground egusi (melon seeds)',
      'Beef (lean cuts)',
      'Bitter leaf (washed)',
      'Palm oil',
      'Crayfish (ground)',
      'Stockfish (soaked)',
      'Tomatoes',
      'Onion',
      'Scotch bonnet',
      'Salt & pepper soup seasoning',
    ],
    preparation: 'Fry egusi paste in palm oil. Add stock, beef, stockfish, and crayfish. Simmer 20 min. Add bitter leaf and cook 5 min.',
    notes: 'GI ≈ 25 (egusi is very low GI). Rich in zinc.',
  },
  {
    id: 'L02',
    name: 'Okra Soup with Assorted Fish',
    gi: 20,
    description: 'Slimy, fibre-rich okra soup loaded with tilapia, smoked fish, and crayfish.',
    ingredients: [
      'Okra (chopped fine)',
      'Tilapia (whole or fillets)',
      'Smoked fish',
      'Crayfish',
      'Palm oil',
      'Onion',
      'Scotch bonnet',
      'Locust beans (iru)',
      'Salt',
    ],
    preparation: 'Fry onion in palm oil, add iru and crayfish. Pour stock, add fish. Add okra last, cook 5–8 min to keep mucilage.',
    notes: 'Okra fibre reduces blood sugar. GI ≈ 20.',
  },
  {
    id: 'L03',
    name: 'Bitter Leaf Soup with Goat Meat',
    gi: 5,
    description: 'Traditional Igbo soup with washed bitter leaf, goat meat, and ground egusi.',
    ingredients: [
      'Bitter leaf (washed, squeezed)',
      'Goat meat',
      'Ground egusi (½ cup)',
      'Palm oil',
      'Crayfish',
      'Stockfish',
      'Onion',
      'Scotch bonnet',
      'Salt',
    ],
    preparation: 'Cook goat meat until tender. Fry egusi in palm oil. Add stock, meat, crayfish, and stockfish. Add bitter leaf, simmer 10 min.',
    notes: 'Bitter leaf lowers blood sugar. GI ≈ 5.',
  },
  {
    id: 'L04',
    name: 'Afang Soup with Periwinkle',
    gi: 10,
    description: 'Afang (wild spinach) and waterleaf soup with periwinkle, beef, and assorted fish.',
    ingredients: [
      'Afang leaves (shredded)',
      'Waterleaf',
      'Periwinkle (cleaned)',
      'Beef',
      'Smoked fish',
      'Crayfish',
      'Palm oil',
      'Stockfish',
      'Onion',
      'Salt & pepper',
    ],
    preparation: 'Cook beef with seasoning. Add periwinkle, fish, crayfish, and palm oil. Add waterleaf then afang leaves. Simmer 10 min.',
    notes: 'Rich in minerals and omega fatty acids. GI ≈ 10.',
  },
  {
    id: 'L05',
    name: 'Edikaikong Soup with Beef & Crayfish',
    gi: 10,
    description: 'Cross River mixed vegetable soup with fluted pumpkin and waterleaf.',
    ingredients: [
      'Fluted pumpkin leaves (ugwu)',
      'Waterleaf',
      'Beef (assorted)',
      'Crayfish',
      'Palm oil',
      'Periwinkle',
      'Stockfish',
      'Onion',
      'Salt',
    ],
    preparation: 'Cook beef until tender. Add crayfish, periwinkle, and palm oil. Stir in waterleaf then ugwu, cook 5 min.',
    notes: 'One of the most nutritious Nigerian soups. GI ≈ 10.',
  },
  {
    id: 'L06',
    name: 'Oha Soup with Goat Meat',
    gi: 15,
    description: 'Delicate oha leaf soup thickened with cocoyam-free achi, served with goat meat.',
    ingredients: [
      'Oha leaves (shredded at the last minute)',
      'Goat meat',
      'Achi (thickener — low GI)',
      'Crayfish',
      'Palm oil',
      'Stockfish',
      'Onion',
      'Salt',
    ],
    preparation: 'Cook goat meat. Add palm oil, crayfish, and achi dissolved in water. Simmer 10 min. Add oha leaves at the end.',
    notes: 'Achi powder is a low-GI thickener. GI ≈ 15.',
  },
  {
    id: 'L07',
    name: 'Efo Riro (Vegetable Stew) with Turkey',
    gi: 5,
    description: 'Yoruba-style leafy vegetable stew with tatashe, turkey, and assorted fish.',
    ingredients: [
      'Soko (Lagos spinach) or ugwu',
      'Turkey (cooked)',
      'Tatashe (red bell pepper)',
      'Scotch bonnet',
      'Onion',
      'Palm oil',
      'Crayfish',
      'Smoked mackerel',
      'Locust beans',
      'Salt',
    ],
    preparation: 'Blend and fry tatashe, onion, and peppers in palm oil. Add turkey, fish, iru, and crayfish. Stir in vegetables, cook 5 min.',
    notes: 'High in iron and vitamins. GI ≈ 5.',
  },
  {
    id: 'L08',
    name: 'Groundnut Soup with Chicken (No Starch)',
    gi: 20,
    description: 'Peanut-based Hausa-inspired soup with chicken and African spices — no rice or swallow.',
    ingredients: [
      'Groundnuts (peanuts, roasted and ground)',
      'Chicken (pieces)',
      'Tomatoes',
      'Onion',
      'Scotch bonnet',
      'Ginger',
      'Salt',
    ],
    preparation: 'Blend tomatoes with pepper. Fry in oil, add chicken stock. Whisk in peanut butter, add chicken. Simmer 15 min.',
    notes: 'Peanuts have GI ≈ 14. High in protein and healthy fats. GI ≈ 20.',
  },
  {
    id: 'L09',
    name: 'Ogbono Soup with Fish',
    gi: 15,
    description: 'Draw soup made from ground wild mango seeds with dried fish and ugwu.',
    ingredients: [
      'Ground ogbono (wild mango seeds)',
      'Smoked fish',
      'Dried fish',
      'Ugwu or bitter leaf',
      'Palm oil',
      'Crayfish',
      'Onion',
      'Scotch bonnet',
      'Salt',
    ],
    preparation: 'Fry ogbono in palm oil until draw. Add stock, fish, and crayfish. Simmer 15 min. Add ugwu at the end.',
    notes: 'Ogbono is rich in healthy fats (similar to mango butter). GI ≈ 15.',
  },
  {
    id: 'L10',
    name: 'Okra & Ogbono Draw Soup with Assorted Meat',
    gi: 15,
    description: 'Double-draw soup combining okra and ogbono with assorted beef, tripe, and fish.',
    ingredients: [
      'Okra (chopped)',
      'Ground ogbono',
      'Beef (assorted: shaki, kpomo)',
      'Smoked fish',
      'Crayfish',
      'Palm oil',
      'Onion',
      'Scotch bonnet',
      'Salt',
    ],
    preparation: 'Cook assorted meat. Fry ogbono in palm oil. Add stock and meat. Add okra and cook 8 min.',
    notes: 'Double fibre source. GI ≈ 15.',
  },
  {
    id: 'L11',
    name: 'Grilled Tilapia with Garden Egg Stew',
    gi: 5,
    description: 'Herb-marinated grilled tilapia with a rich garden egg and tomato sauce.',
    ingredients: [
      'Tilapia (whole)',
      'African eggplant (garden egg)',
      'Tomatoes (3)',
      'Onion',
      'Scotch bonnet',
      'Scent leaf',
      'Garlic',
      'Ginger',
      'Palm oil (1 tsp)',
      'Salt & pepper',
    ],
    preparation: 'Marinate tilapia with garlic, ginger, salt. Grill 20 min. Blend garden egg and tomatoes, fry in oil with onion. Serve with fish.',
    notes: 'Garden egg (eggplant) is hypoglycemic. GI ≈ 5.',
  },
  {
    id: 'L12',
    name: 'Catfish Stew with Ugwu',
    gi: 0,
    description: 'Succulent catfish in a tomato stew loaded with fluted pumpkin leaves.',
    ingredients: [
      'Catfish (large piece)',
      'Ugwu leaves',
      'Tomatoes (3)',
      'Onion',
      'Scotch bonnet',
      'Scent leaf',
      'Palm oil (1 tsp)',
      'Crayfish',
      'Salt',
    ],
    preparation: 'Blend tomatoes. Fry in palm oil with onion and crayfish. Add catfish and simmer 15 min. Stir in ugwu and scent leaf.',
    notes: 'GI ≈ 0. High omega-3.',
  },
  {
    id: 'L13',
    name: 'Smoked Mackerel in Tomato Stew',
    gi: 0,
    description: 'Classic Nigerian tomato stew with chunks of smoked mackerel (titus) fish.',
    ingredients: [
      'Smoked mackerel (titus)',
      'Tomatoes (4)',
      'Tatashe',
      'Scotch bonnet',
      'Onion',
      'Palm oil',
      'Curry & thyme',
      'Salt',
    ],
    preparation: 'Blend tomatoes and peppers. Fry in palm oil with onion, curry, and thyme. Add mackerel and simmer 10 min.',
    notes: 'Omega-3 rich. GI ≈ 0.',
  },
  {
    id: 'L14',
    name: 'Grilled Chicken with Vegetable Salad',
    gi: 0,
    description: 'Herb-spiced grilled chicken breast over a crisp Nigerian-style vegetable salad.',
    ingredients: [
      'Chicken breast',
      'Cucumber',
      'Tomatoes',
      'Lettuce',
      'Garden egg',
      'Onion',
      'Scent leaf',
      'Lemon juice',
      'Garlic powder',
      'Turmeric, pepper, salt (marinade)',
    ],
    preparation: 'Marinate and grill chicken 30 min. Combine salad vegetables. Drizzle with lemon, add scent leaf.',
    notes: 'GI ≈ 0.',
  },
  {
    id: 'L15',
    name: 'Goat Meat Stew with Ugwu',
    gi: 0,
    description: 'Slow-simmered goat meat in a tomato-pepper stew with fresh pumpkin leaves.',
    ingredients: [
      'Goat meat',
      'Ugwu',
      'Tomatoes (4)',
      'Onion',
      'Scotch bonnet',
      'Garlic',
      'Ginger',
      'Palm oil',
      'Salt & spices',
    ],
    preparation: 'Cook goat meat until tender. Fry tomato-pepper blend with garlic and ginger. Add meat, simmer 15 min. Add ugwu last.',
    notes: 'GI ≈ 0.',
  },
  {
    id: 'L16',
    name: 'Turkey Stew with Mixed Vegetables',
    gi: 0,
    description: 'Lean turkey in a rich stew with bitter leaf, scent leaf, and tomatoes.',
    ingredients: [
      'Turkey (pieces)',
      'Bitter leaf',
      'Scent leaf',
      'Tomatoes (3)',
      'Onion',
      'Scotch bonnet',
      'Palm oil',
      'Crayfish',
      'Salt',
    ],
    preparation: 'Cook turkey with spices. Fry tomato blend in palm oil. Add turkey and crayfish. Stir in bitter leaf and scent leaf.',
    notes: 'GI ≈ 0.',
  },
  {
    id: 'L17',
    name: 'Baked Tilapia with Herb Sauce',
    gi: 0,
    description: 'Oven-baked tilapia rubbed with ginger, garlic, turmeric, and scent leaf.',
    ingredients: [
      'Tilapia (whole or fillets)',
      'Scent leaf (blended)',
      'Garlic (5 cloves)',
      'Ginger (2 tsp)',
      'Turmeric (½ tsp)',
      'Lemon juice',
      'Tomatoes (2)',
      'Salt & pepper',
    ],
    preparation: 'Blend scent leaf, garlic, ginger, and turmeric into a paste. Coat tilapia. Bake at 180°C for 25 min.',
    notes: 'No oil needed. GI ≈ 0.',
  },
  {
    id: 'L18',
    name: 'Prawn Stir-fry with Vegetables',
    gi: 0,
    description: 'Jumbo prawns stir-fried with okra, garden egg, and locust beans.',
    ingredients: [
      'Prawns (jumbo)',
      'Okra (sliced)',
      'Garden egg',
      'Locust beans (iru)',
      'Onion',
      'Scotch bonnet',
      'Palm oil (1 tsp)',
      'Scent leaf',
      'Salt',
    ],
    preparation: 'Sauté onion and iru in palm oil. Add prawns, okra, and garden egg. Cook 8 min. Finish with scent leaf.',
    notes: 'GI ≈ 0.',
  },
  {
    id: 'L19',
    name: 'Moimoi with Chicken Stew',
    gi: 30,
    description: 'Protein-packed bean pudding served alongside a rich chicken and vegetable stew.',
    ingredients: [
      'Black-eyed peas (moimoi)',
      'Chicken (stewed)',
      'Tomatoes',
      'Onion',
      'Scotch bonnet',
      'Ugwu or bitter leaf',
      'Palm oil',
      'Crayfish',
      'Salt',
    ],
    preparation: 'Prepare moimoi as standard. Make chicken stew with tomatoes, palm oil, ugwu, and crayfish.',
    notes: 'GI ≈ 30.',
  },
  {
    id: 'L20',
    name: 'Bean Stew with Assorted Fish',
    gi: 28,
    description: 'Slow-cooked brown beans in tomato stew with smoked, dried, and fresh fish.',
    ingredients: [
      'Brown beans (cooked)',
      'Smoked fish',
      'Dried fish',
      'Tomatoes (3)',
      'Onion',
      'Palm oil',
      'Scotch bonnet',
      'Crayfish',
      'Locust beans',
      'Salt',
    ],
    preparation: 'Fry blended tomatoes in palm oil. Add all fish and locust beans. Stir in cooked beans and simmer 15 min.',
    notes: 'GI ≈ 28.',
  },
  {
    id: 'L21',
    name: 'Snail Stew with Vegetables',
    gi: 0,
    description: 'Tender garden snails in a tomato-pepper stew with ugwu and scent leaf.',
    ingredients: [
      'Garden snails',
      'Ugwu',
      'Tomatoes (3)',
      'Onion',
      'Scotch bonnet',
      'Scent leaf',
      'Palm oil',
      'Crayfish',
      'Salt',
    ],
    preparation: 'Clean and parboil snails. Fry tomato blend in palm oil. Add snails and crayfish, simmer 15 min. Add ugwu and scent leaf.',
    notes: 'Very low fat. GI ≈ 0.',
  },
  {
    id: 'L22',
    name: 'Cowpeas Stew with Lean Beef',
    gi: 28,
    description: 'Black-eyed peas cooked with tender beef pieces and African herbs.',
    ingredients: [
      'Cowpeas (black-eyed peas)',
      'Lean beef',
      'Tomatoes (2)',
      'Onion',
      'Scotch bonnet',
      'Palm oil',
      'Crayfish',
      'Locust beans',
      'Salt & seasoning',
    ],
    preparation: 'Cook beef until tender. Cook cowpeas until soft. Combine in tomato-palm oil base with crayfish.',
    notes: 'GI ≈ 28.',
  },
  {
    id: 'L23',
    name: 'Grilled Catfish with Pepper Sauce',
    gi: 0,
    description: 'Whole grilled catfish served with a fresh chilli-tomato pepper sauce.',
    ingredients: [
      'Catfish (whole)',
      'Fresh tomatoes (3)',
      'Scotch bonnet',
      'Onion',
      'Scent leaf',
      'Garlic',
      'Ginger',
      'Lemon juice',
      'Salt',
    ],
    preparation: 'Marinate catfish with garlic, ginger, lemon. Grill over charcoal or oven-grill 25 min. Blend raw pepper sauce.',
    notes: 'GI ≈ 0.',
  },
  {
    id: 'L24',
    name: 'Chicken Groundnut Stew (No Starch)',
    gi: 20,
    description: 'Northern Nigeria-style groundnut stew with chicken, tomatoes, and ginger.',
    ingredients: [
      'Chicken',
      'Groundnut paste (peanut butter, no sugar)',
      'Tomatoes (3)',
      'Onion',
      'Ginger',
      'Garlic',
      'Scotch bonnet',
      'Spinach',
      'Salt',
    ],
    preparation: 'Cook chicken with onion. Blend tomatoes, fry with garlic and ginger. Add groundnut paste and chicken, simmer 20 min.',
    notes: 'GI ≈ 20.',
  },
  {
    id: 'L25',
    name: 'Vegetable Stew with Smoked Fish',
    gi: 5,
    description: 'Garden-fresh tomato stew loaded with smoked mackerel and bitter leaf.',
    ingredients: [
      'Smoked mackerel',
      'Bitter leaf or ugwu',
      'Tomatoes (4)',
      'Tatashe',
      'Onion',
      'Palm oil',
      'Crayfish',
      'Salt',
    ],
    preparation: 'Blend and fry tomatoes and peppers. Add fish, crayfish. Stir in vegetables and cook 5 min.',
    notes: 'GI ≈ 5.',
  },
  {
    id: 'L26',
    name: 'Mackerel Pepper Soup',
    gi: 0,
    description: 'Fresh whole mackerel in spiced pepper soup broth with uziza and scent leaf.',
    ingredients: [
      'Fresh mackerel (whole)',
      'Pepper soup spice blend',
      'Ginger',
      'Onion',
      'Scent leaf',
      'Uziza leaves',
      'Scotch bonnet',
      'Salt',
    ],
    preparation: 'Parboil mackerel 5 min. Add spices, ginger, and onion. Simmer 20 min. Add uziza and scent leaf.',
    notes: 'GI ≈ 0. High in omega-3 and vitamin D.',
  },
  {
    id: 'L27',
    name: 'Beef Stir-fry with Ugwu Leaves',
    gi: 0,
    description: 'Lean beef strips stir-fried with fluted pumpkin leaves and African spices.',
    ingredients: [
      'Beef (sirloin strips)',
      'Ugwu (fluted pumpkin leaves)',
      'Onion',
      'Garlic',
      'Ginger',
      'Scotch bonnet',
      'Scent leaf',
      'Coconut oil (1 tsp)',
      'Salt',
    ],
    preparation: 'Marinate beef with garlic, ginger, and salt. Stir-fry over high heat 5 min. Add ugwu and cook 3 min.',
    notes: 'GI ≈ 0.',
  },
  {
    id: 'L28',
    name: 'Prawns in Tomato & Garden Egg Sauce',
    gi: 5,
    description: 'Plump prawns simmered in a creamy garden egg and tomato sauce.',
    ingredients: [
      'Prawns',
      'Garden egg (African eggplant)',
      'Tomatoes (3)',
      'Onion',
      'Scotch bonnet',
      'Scent leaf',
      'Palm oil (1 tsp)',
      'Garlic',
      'Salt',
    ],
    preparation: 'Grill garden eggs, blend with tomatoes. Fry onion in oil, add sauce. Add prawns and simmer 10 min.',
    notes: 'GI ≈ 5.',
  },
  {
    id: 'L29',
    name: 'Lentil African Soup',
    gi: 32,
    description: 'Red lentil soup with smoked fish, tomatoes, and African spice mix.',
    ingredients: [
      'Red lentils',
      'Smoked fish',
      'Tomatoes (2)',
      'Onion',
      'Garlic',
      'Ginger',
      'Turmeric',
      'Scent leaf',
      'Salt',
    ],
    preparation: 'Boil lentils until soft. Fry tomato blend with garlic and ginger. Combine with lentils. Add fish and simmer 10 min.',
    notes: 'GI ≈ 32.',
  },
  {
    id: 'L30',
    name: 'Egusi Soup with Uziza & Goat Meat',
    gi: 25,
    description: 'Egusi soup enriched with peppery uziza leaves and tender goat meat.',
    ingredients: [
      'Ground egusi',
      'Goat meat',
      'Uziza leaves',
      'Palm oil',
      'Crayfish',
      'Stockfish',
      'Tomatoes',
      'Onion',
      'Scotch bonnet',
      'Salt',
    ],
    preparation: 'Fry egusi in palm oil. Add stock, goat meat, fish, and crayfish. Simmer 20 min. Add uziza at the end.',
    notes: 'GI ≈ 25.',
  },
];

// ─────────────────────────────────────────────
//  DINNER POOL  (30 options, GI ≤ 55)
// ─────────────────────────────────────────────
const DINNERS = [
  {
    id: 'D01',
    name: 'Grilled Tilapia with Bitter Leaf Soup',
    gi: 5,
    description: 'Light dinner of grilled tilapia alongside a small bowl of bitter leaf soup.',
    ingredients: [
      'Tilapia (grilled)',
      'Bitter leaf (washed)',
      'Ground egusi (2 tbsp)',
      'Palm oil',
      'Crayfish',
      'Stockfish',
      'Salt',
    ],
    preparation: 'Grill tilapia. Prepare bitter leaf soup with minimal egusi. Serve together.',
    notes: 'Light, anti-diabetic dinner. GI ≈ 5.',
  },
  {
    id: 'D02',
    name: 'Chicken Pepper Soup (Evening)',
    gi: 0,
    description: 'Soothing chicken pepper soup with utazi — ideal for a light, anti-inflammatory evening meal.',
    ingredients: [
      'Chicken pieces',
      'Pepper soup spice blend',
      'Utazi leaf',
      'Scent leaf',
      'Ginger',
      'Onion',
      'Salt',
    ],
    preparation: 'Cook chicken with spices and onion. Simmer 25 min. Add utazi and scent leaf.',
    notes: 'GI ≈ 0. Low on digestion at night.',
  },
  {
    id: 'D03',
    name: 'Goat Meat Stew with Garden Egg',
    gi: 5,
    description: 'Tender goat meat in a garden egg and tomato stew with scent leaf.',
    ingredients: [
      'Goat meat',
      'Garden egg',
      'Tomatoes (3)',
      'Onion',
      'Scotch bonnet',
      'Scent leaf',
      'Palm oil',
      'Crayfish',
      'Salt',
    ],
    preparation: 'Cook goat meat. Grill and blend garden egg with tomatoes. Fry stew, add meat. Add scent leaf.',
    notes: 'GI ≈ 5.',
  },
  {
    id: 'D04',
    name: 'Smoked Fish Vegetable Soup',
    gi: 5,
    description: 'Wholesome vegetable soup with multiple smoked fish varieties.',
    ingredients: [
      'Smoked mackerel',
      'Smoked catfish',
      'Ugwu or waterleaf',
      'Palm oil',
      'Crayfish',
      'Onion',
      'Scotch bonnet',
      'Locust beans',
      'Salt',
    ],
    preparation: 'Prepare light tomato base. Add all fish. Stir in vegetables and cook 5 min.',
    notes: 'GI ≈ 5.',
  },
  {
    id: 'D05',
    name: 'Prawn Okra Soup',
    gi: 20,
    description: 'Viscous okra soup with fresh prawns and locust beans — evening fibre boost.',
    ingredients: [
      'Prawns (deveined)',
      'Okra (finely chopped)',
      'Locust beans (iru)',
      'Palm oil',
      'Crayfish',
      'Onion',
      'Scotch bonnet',
      'Scent leaf',
      'Salt',
    ],
    preparation: 'Fry onion and iru in palm oil. Add crayfish and okra. Pour stock, add prawns. Cook 8 min.',
    notes: 'Fibre-rich. GI ≈ 20.',
  },
  {
    id: 'D06',
    name: 'Beef Efo Riro',
    gi: 5,
    description: 'Classic Yoruba vegetable stew with lean beef, soko (Lagos spinach), and iru.',
    ingredients: [
      'Soko or ugwu',
      'Lean beef',
      'Tatashe (red bell pepper)',
      'Onion',
      'Palm oil',
      'Locust beans (iru)',
      'Crayfish',
      'Scotch bonnet',
      'Salt',
    ],
    preparation: 'Cook beef. Fry blended tatashe and onion in palm oil with iru. Add beef and crayfish. Stir in vegetables.',
    notes: 'GI ≈ 5.',
  },
  {
    id: 'D07',
    name: 'Catfish Banga Soup',
    gi: 15,
    description: 'Delta-style palm nut broth with catfish, scent leaf, and oburunbebe stick.',
    ingredients: [
      'Palm nut cream (canned)',
      'Catfish',
      'Scent leaf',
      'Oburunbebe stick or bay leaf',
      'Onion',
      'Crayfish',
      'Dried fish',
      'Salt & pepper',
    ],
    preparation: 'Boil palm nut cream. Add onion, crayfish, dried fish, and oburunbebe. Add catfish and simmer 20 min. Add scent leaf.',
    notes: 'GI ≈ 15.',
  },
  {
    id: 'D08',
    name: 'Turkey Afang Soup',
    gi: 10,
    description: 'Wild spinach (afang) soup with tender turkey pieces and periwinkle.',
    ingredients: [
      'Afang leaves (shredded)',
      'Waterleaf',
      'Turkey (cooked)',
      'Periwinkle',
      'Palm oil',
      'Crayfish',
      'Stockfish',
      'Onion',
      'Salt',
    ],
    preparation: 'Cook turkey. Combine with palm oil, crayfish, and periwinkle in a pot. Add waterleaf then afang. Simmer 8 min.',
    notes: 'GI ≈ 10.',
  },
  {
    id: 'D09',
    name: 'Snail and Vegetable Stew',
    gi: 0,
    description: 'Garden snails in a light, herby vegetable stew — a low-fat evening meal.',
    ingredients: [
      'Garden snails',
      'Ugwu',
      'Tomatoes (3)',
      'Onion',
      'Scent leaf',
      'Palm oil (1 tsp)',
      'Crayfish',
      'Scotch bonnet',
      'Salt',
    ],
    preparation: 'Clean snails. Fry tomato blend in palm oil. Add snails and crayfish, simmer 20 min. Stir in ugwu and scent leaf.',
    notes: 'GI ≈ 0.',
  },
  {
    id: 'D10',
    name: 'Grilled Mackerel with Okra Sauce',
    gi: 20,
    description: 'Charcoal-grilled whole mackerel served with a thick okra sauce.',
    ingredients: [
      'Whole mackerel',
      'Okra (sliced)',
      'Tomatoes (2)',
      'Onion',
      'Scotch bonnet',
      'Crayfish',
      'Palm oil (1 tsp)',
      'Scent leaf',
      'Salt',
    ],
    preparation: 'Grill mackerel. Make okra sauce with tomatoes, crayfish, and palm oil. Pour over fish.',
    notes: 'GI ≈ 20.',
  },
  {
    id: 'D11',
    name: 'Chicken Groundnut Soup (No Starch)',
    gi: 20,
    description: 'Peanut-based chicken soup — filling, protein-rich evening meal.',
    ingredients: [
      'Chicken pieces',
      'Natural peanut butter (no sugar)',
      'Tomatoes (3)',
      'Onion',
      'Ginger',
      'Garlic',
      'Ugwu',
      'Salt',
    ],
    preparation: 'Cook chicken. Blend tomatoes, fry with garlic. Add peanut butter and chicken stock. Simmer. Add ugwu.',
    notes: 'GI ≈ 20.',
  },
  {
    id: 'D12',
    name: 'Cowpeas & Vegetable Porridge',
    gi: 28,
    description: 'Brown beans cooked with vegetables and spices — a comforting, low-GI dinner.',
    ingredients: [
      'Brown beans or cowpeas',
      'Ugwu or bitter leaf',
      'Onion',
      'Scotch bonnet',
      'Palm oil',
      'Crayfish',
      'Salt',
    ],
    preparation: 'Cook beans until tender. Add onion, pepper, crayfish, and palm oil. Stir in vegetables, cook 5 min.',
    notes: 'GI ≈ 28.',
  },
  {
    id: 'D13',
    name: 'Lentil Vegetable Soup (African Style)',
    gi: 32,
    description: 'Spiced red lentil soup with smoked fish, ugwu, and ginger.',
    ingredients: [
      'Red lentils',
      'Smoked fish',
      'Ugwu',
      'Tomatoes (2)',
      'Onion',
      'Garlic',
      'Ginger',
      'Turmeric',
      'Salt',
    ],
    preparation: 'Cook lentils. Fry tomato, garlic, ginger, turmeric. Combine with lentils and fish. Add ugwu.',
    notes: 'GI ≈ 32.',
  },
  {
    id: 'D14',
    name: 'Beef Egusi Soup',
    gi: 25,
    description: 'Rich egusi soup with assorted beef and bitter leaf — classic Nigerian dinner.',
    ingredients: [
      'Ground egusi',
      'Beef (assorted)',
      'Bitter leaf',
      'Palm oil',
      'Crayfish',
      'Stockfish',
      'Onion',
      'Scotch bonnet',
      'Salt',
    ],
    preparation: 'Cook beef. Fry egusi in palm oil. Add stock, beef, and crayfish. Add bitter leaf and simmer.',
    notes: 'GI ≈ 25.',
  },
  {
    id: 'D15',
    name: 'Prawn & Ugwu Stir-fry',
    gi: 0,
    description: 'Quick high-protein dinner of prawns stir-fried with pumpkin leaves and garlic.',
    ingredients: [
      'Prawns',
      'Ugwu',
      'Garlic (4 cloves)',
      'Ginger',
      'Onion',
      'Tomato',
      'Scotch bonnet',
      'Coconut oil (1 tsp)',
      'Salt',
    ],
    preparation: 'Stir-fry garlic and ginger in oil. Add prawns and cook 3 min. Add tomatoes, onion, and ugwu. Cook 5 min.',
    notes: 'GI ≈ 0.',
  },
  {
    id: 'D16',
    name: 'Grilled Goat Meat with Vegetables',
    gi: 0,
    description: 'Spiced grilled goat meat served alongside a garden egg and tomato salad.',
    ingredients: [
      'Goat meat (chunks)',
      'Garden egg',
      'Tomatoes',
      'Onion',
      'Garlic',
      'Ginger',
      'Scotch bonnet',
      'Scent leaf',
      'Lemon juice',
      'Salt & pepper',
    ],
    preparation: 'Marinate goat meat with garlic, ginger, and spices. Grill 35 min. Serve with garden egg-tomato salad.',
    notes: 'GI ≈ 0.',
  },
  {
    id: 'D17',
    name: 'Turkey Pepper Soup',
    gi: 0,
    description: 'Lean turkey pepper soup with uziza and scent leaf — perfect evening sip.',
    ingredients: [
      'Turkey (pieces)',
      'Pepper soup spices',
      'Uziza leaves',
      'Scent leaf',
      'Ginger',
      'Onion',
      'Scotch bonnet',
      'Salt',
    ],
    preparation: 'Cook turkey with spices and onion until tender. Add uziza and scent leaf.',
    notes: 'GI ≈ 0.',
  },
  {
    id: 'D18',
    name: 'Catfish Stew with Bitter Leaf',
    gi: 5,
    description: 'Catfish in a rich palm oil stew with bitter leaf and ground crayfish.',
    ingredients: [
      'Catfish',
      'Bitter leaf (washed)',
      'Tomatoes (3)',
      'Onion',
      'Scotch bonnet',
      'Palm oil',
      'Crayfish',
      'Salt',
    ],
    preparation: 'Fry tomato-pepper blend. Add catfish and crayfish. Simmer 15 min. Stir in bitter leaf.',
    notes: 'GI ≈ 5.',
  },
  {
    id: 'D19',
    name: 'Edikaikong with Periwinkle',
    gi: 10,
    description: 'Nutritious Cross River mixed-leaf soup with periwinkle and smoked fish.',
    ingredients: [
      'Ugwu',
      'Waterleaf',
      'Periwinkle',
      'Smoked fish',
      'Palm oil',
      'Crayfish',
      'Onion',
      'Salt',
    ],
    preparation: 'Combine palm oil, crayfish, periwinkle, and fish. Cook 5 min. Add waterleaf then ugwu. Cook 5 min.',
    notes: 'GI ≈ 10.',
  },
  {
    id: 'D20',
    name: 'Oha Soup with Beef',
    gi: 15,
    description: 'Aromatic oha leaf soup thickened with achi, served with tender beef.',
    ingredients: [
      'Oha leaves (shredded)',
      'Beef',
      'Achi (thickener)',
      'Crayfish',
      'Stockfish',
      'Palm oil',
      'Onion',
      'Salt',
    ],
    preparation: 'Cook beef. Add palm oil, crayfish, achi paste. Simmer 10 min. Add oha leaves at the end.',
    notes: 'GI ≈ 15.',
  },
  {
    id: 'D21',
    name: 'Ogbono Soup with Turkey',
    gi: 15,
    description: 'Draw soup made with wild mango seeds (ogbono) and lean turkey.',
    ingredients: [
      'Ground ogbono',
      'Turkey',
      'Ugwu or bitter leaf',
      'Palm oil',
      'Crayfish',
      'Stockfish',
      'Onion',
      'Salt',
    ],
    preparation: 'Fry ogbono in palm oil until sticky. Add stock and turkey. Simmer 20 min. Add vegetables.',
    notes: 'GI ≈ 15.',
  },
  {
    id: 'D22',
    name: 'Cow Tail Pepper Soup',
    gi: 0,
    description: 'Gelatinous cow tail pieces in a warming spiced pepper soup broth.',
    ingredients: [
      'Cow tail',
      'Pepper soup spices',
      'Ginger',
      'Garlic',
      'Onion',
      'Scent leaf',
      'Scotch bonnet',
      'Salt',
    ],
    preparation: 'Pressure-cook cow tail 40 min. Add spices and simmer 20 min. Add scent leaf.',
    notes: 'Collagen-rich. GI ≈ 0.',
  },
  {
    id: 'D23',
    name: 'Smoked Sardine with Garden Egg Stew',
    gi: 5,
    description: 'Smoked sardines in a chunky garden egg and tomato stew.',
    ingredients: [
      'Smoked sardines',
      'Garden egg (grilled, blended)',
      'Tomatoes (3)',
      'Onion',
      'Scotch bonnet',
      'Scent leaf',
      'Palm oil',
      'Crayfish',
      'Salt',
    ],
    preparation: 'Blend garden egg with tomatoes. Fry in palm oil. Add sardines and crayfish. Simmer 10 min.',
    notes: 'GI ≈ 5.',
  },
  {
    id: 'D24',
    name: 'Prawn Draw Soup',
    gi: 20,
    description: 'Okra draw soup with large prawns and locust beans.',
    ingredients: [
      'Prawns',
      'Okra (chopped)',
      'Locust beans (iru)',
      'Palm oil',
      'Crayfish',
      'Onion',
      'Scotch bonnet',
      'Scent leaf',
      'Salt',
    ],
    preparation: 'Fry onion and iru in palm oil. Add crayfish. Pour stock, add okra and prawns. Cook 10 min.',
    notes: 'GI ≈ 20.',
  },
  {
    id: 'D25',
    name: 'Chicken Waterleaf Soup',
    gi: 0,
    description: 'Light, hydrating waterleaf soup with chicken and African herbs.',
    ingredients: [
      'Chicken (boneless)',
      'Waterleaf',
      'Onion',
      'Scotch bonnet',
      'Crayfish',
      'Palm oil (1 tsp)',
      'Scent leaf',
      'Salt',
    ],
    preparation: 'Cook chicken with onion and spices. Add crayfish and palm oil. Stir in waterleaf. Cook 5 min.',
    notes: 'GI ≈ 0.',
  },
  {
    id: 'D26',
    name: 'Grilled Tilapia with Efo Riro',
    gi: 5,
    description: 'Grilled tilapia fillets served with a side of Yoruba vegetable stew.',
    ingredients: [
      'Tilapia (fillets)',
      'Soko or ugwu',
      'Tatashe (red bell pepper)',
      'Onion',
      'Palm oil',
      'Iru',
      'Crayfish',
      'Salt',
    ],
    preparation: 'Grill tilapia fillets. Make efo riro with tatashe, onion, iru, and vegetables.',
    notes: 'GI ≈ 5.',
  },
  {
    id: 'D27',
    name: 'Moimoi with Fish Stew',
    gi: 30,
    description: 'Steamed bean pudding served with a light tomato-fish stew for dinner.',
    ingredients: [
      'Black-eyed peas (moimoi)',
      'Smoked fish',
      'Tomatoes (3)',
      'Onion',
      'Scotch bonnet',
      'Palm oil',
      'Ugwu',
      'Crayfish',
      'Salt',
    ],
    preparation: 'Steam moimoi. Prepare fish stew with tomatoes, palm oil, fish, and ugwu.',
    notes: 'GI ≈ 30.',
  },
  {
    id: 'D28',
    name: 'Mackerel in African Herb Sauce',
    gi: 0,
    description: 'Mackerel fillets poached in a scent leaf, garlic, and tomato herb sauce.',
    ingredients: [
      'Mackerel fillets',
      'Scent leaf (blended)',
      'Garlic (5 cloves)',
      'Ginger',
      'Tomatoes (2)',
      'Onion',
      'Scotch bonnet',
      'Salt',
    ],
    preparation: 'Blend scent leaf, garlic, and ginger. Fry with tomatoes. Add mackerel and poach 12 min.',
    notes: 'GI ≈ 0. Omega-3 rich.',
  },
  {
    id: 'D29',
    name: 'Beef & Vegetable Stir-fry',
    gi: 0,
    description: 'Lean beef stir-fried with garden egg, ugwu, and African spices.',
    ingredients: [
      'Lean beef strips',
      'Garden egg',
      'Ugwu',
      'Onion',
      'Garlic',
      'Ginger',
      'Scotch bonnet',
      'Coconut oil (1 tsp)',
      'Salt',
    ],
    preparation: 'Marinate beef. Stir-fry with garlic and ginger. Add garden egg and ugwu. Cook 5 min.',
    notes: 'GI ≈ 0.',
  },
  {
    id: 'D30',
    name: 'Snail Pepper Soup',
    gi: 0,
    description: 'Garden snail pepper soup — a delicacy perfect for evening blood sugar management.',
    ingredients: [
      'Garden snails (cleaned)',
      'Pepper soup spice blend',
      'Ginger',
      'Scent leaf',
      'Utazi leaf',
      'Onion',
      'Salt',
    ],
    preparation: 'Parboil snails. Cook with pepper soup spices and onion 25 min. Add scent leaf.',
    notes: 'GI ≈ 0.',
  },
];

// ─────────────────────────────────────────────
//  DRINK POOL  (20 options)
// ─────────────────────────────────────────────
const DRINKS = [
  {
    id: 'DR01',
    name: 'Unsweetened Zobo (Hibiscus) Tea',
    description: 'Tart, ruby-red hibiscus tea — clinically shown to lower blood pressure and blood sugar.',
    ingredients: [
      'Dried hibiscus flowers (zobo leaves)',
      'Ginger (fresh slices)',
      'Cloves (3)',
      'Cinnamon stick',
      'Lemon juice',
      'Cold water',
    ],
    preparation: 'Steep zobo petals, ginger, cloves, and cinnamon in hot water 20 min. Strain, cool, and refrigerate. Add lemon juice before serving. NO sweetener.',
    benefits: 'Lowers blood sugar and blood pressure. Rich in antioxidants.',
  },
  {
    id: 'DR02',
    name: 'Ginger-Turmeric Tea',
    description: 'Warming anti-inflammatory brew with fresh ginger and turmeric.',
    ingredients: [
      'Fresh ginger root (5 slices)',
      'Turmeric powder (½ tsp) or fresh',
      'Black pepper (pinch — activates turmeric)',
      'Lemon juice',
      'Water (2 cups)',
    ],
    preparation: 'Boil ginger and turmeric in water 10 min. Strain. Add lemon juice and black pepper. Drink warm.',
    benefits: 'Reduces inflammation, improves insulin sensitivity.',
  },
  {
    id: 'DR03',
    name: 'Bitter Leaf Juice',
    description: 'Freshly squeezed bitter leaf (vernonia) juice — a powerful blood sugar reducer.',
    ingredients: [
      'Fresh bitter leaves (vernonia amygdalina)',
      'Water (1 cup)',
      'Lemon juice (½)',
    ],
    preparation: 'Wash leaves thoroughly. Squeeze the juice by kneading leaves in water. Strain through cloth. Add lemon juice. Drink fresh.',
    benefits: 'Clinically proven to lower blood glucose. Antimicrobial.',
  },
  {
    id: 'DR04',
    name: 'Moringa Leaf Tea',
    description: 'Nutrient-dense moringa tea — rich in vitamins, minerals, and blood-sugar-lowering compounds.',
    ingredients: [
      'Dried moringa leaves (1 tbsp)',
      'Water (2 cups)',
      'Ginger (optional)',
      'Lemon juice',
    ],
    preparation: 'Steep dried moringa in hot (not boiling) water 5 min. Strain. Add lemon. Do not add sweetener.',
    benefits: 'Lowers fasting blood sugar. Rich in protein and iron.',
  },
  {
    id: 'DR05',
    name: 'Cucumber-Lemon Water',
    description: 'Refreshing detox water with cucumber, lemon, and mint.',
    ingredients: [
      'Cucumber (½, sliced)',
      'Lemon (1, sliced)',
      'Fresh mint leaves (5)',
      'Cold water (1 litre)',
    ],
    preparation: 'Combine all in a jug. Refrigerate 2 hours minimum. Drink throughout the day.',
    benefits: 'Hydrating, low GI, supports kidney function.',
  },
  {
    id: 'DR06',
    name: 'Soursop Leaf Tea',
    description: 'Herbal tea from soursop (graviola) leaves — powerful anti-diabetic and antioxidant properties.',
    ingredients: [
      'Dried soursop leaves (3–4)',
      'Water (2 cups)',
      'Ginger (optional)',
      'Lemon juice',
    ],
    preparation: 'Boil soursop leaves in water 15 min. Strain and cool slightly. Add lemon juice.',
    benefits: 'Reduces blood glucose, anti-tumour, anti-inflammatory.',
  },
  {
    id: 'DR07',
    name: 'Scent Leaf (Efirin) Tea',
    description: 'Aromatic tea from African basil — used traditionally to manage blood sugar.',
    ingredients: [
      'Fresh scent leaves (efirin / African basil, 10–15 leaves)',
      'Water (2 cups)',
      'Ginger (2 slices)',
      'Lemon juice',
    ],
    preparation: 'Steep scent leaves and ginger in hot water 10 min. Strain. Add lemon juice.',
    benefits: 'Lowers blood sugar, antimalarial, digestive.',
  },
  {
    id: 'DR08',
    name: 'Cinnamon Tea',
    description: 'Comforting cinnamon tea that improves insulin sensitivity.',
    ingredients: [
      'Cinnamon sticks (2) or 1 tsp ground cinnamon',
      'Water (2 cups)',
      'Ginger (optional)',
      'Lemon juice',
    ],
    preparation: 'Boil cinnamon in water 10 min. Strain. Cool. Add lemon juice.',
    benefits: 'Improves insulin sensitivity. Lowers fasting blood sugar.',
  },
  {
    id: 'DR09',
    name: 'Garlic-Ginger Water',
    description: 'Strong detox water infused with crushed garlic and fresh ginger.',
    ingredients: [
      'Garlic (3 cloves, crushed)',
      'Ginger (5 slices)',
      'Water (1 litre)',
      'Lemon juice',
    ],
    preparation: 'Combine garlic and ginger in water. Refrigerate overnight. Strain and drink in the morning.',
    benefits: 'Lowers blood glucose, anti-inflammatory, boosts metabolism.',
  },
  {
    id: 'DR10',
    name: 'Lemon Water with Turmeric',
    description: 'Simple yet powerful morning drink combining lemon and turmeric.',
    ingredients: [
      'Lemon (1, juiced)',
      'Turmeric powder (¼ tsp)',
      'Black pepper (pinch)',
      'Warm water (1 glass)',
    ],
    preparation: 'Mix all ingredients in warm water. Drink on an empty stomach in the morning.',
    benefits: 'Detoxifying, improves insulin function, anti-inflammatory.',
  },
  {
    id: 'DR11',
    name: 'Uziza (African Black Pepper) Tea',
    description: 'Spicy tea from uziza seeds or leaves — digestive and blood sugar support.',
    ingredients: [
      'Uziza leaves or seeds',
      'Ginger (3 slices)',
      'Water (2 cups)',
      'Lemon juice',
    ],
    preparation: 'Boil uziza with ginger in water 10 min. Strain. Add lemon juice.',
    benefits: 'Digestive aid, antioxidant, blood sugar support.',
  },
  {
    id: 'DR12',
    name: 'Bay Leaf Tea',
    description: 'Mild herbal tea with bay leaves — clinically linked to improved blood glucose control.',
    ingredients: [
      'Bay leaves (3–4 dried)',
      'Cinnamon (½ stick)',
      'Ginger (optional)',
      'Water (2 cups)',
      'Lemon juice',
    ],
    preparation: 'Boil bay leaves and cinnamon in water 10 min. Strain. Add lemon.',
    benefits: 'Lowers blood glucose, improves insulin function.',
  },
  {
    id: 'DR13',
    name: 'Guava Leaf Tea',
    description: 'Tea brewed from guava leaves — proven to slow post-meal blood sugar rises.',
    ingredients: [
      'Fresh or dried guava leaves (4–5)',
      'Water (2 cups)',
      'Ginger (optional)',
    ],
    preparation: 'Boil guava leaves in water 12 min. Strain and cool slightly.',
    benefits: 'Inhibits alpha-glucosidase, slowing glucose absorption after meals.',
  },
  {
    id: 'DR14',
    name: 'Fenugreek Seed Water',
    description: 'Overnight-soaked fenugreek seeds in water — a potent blood sugar remedy.',
    ingredients: [
      'Fenugreek seeds (1 tsp)',
      'Water (1 glass)',
      'Lemon juice (optional)',
    ],
    preparation: 'Soak fenugreek seeds in water overnight. Drink the water (with seeds) on an empty stomach.',
    benefits: 'Rich in fibre, slows glucose absorption, improves insulin sensitivity.',
  },
  {
    id: 'DR15',
    name: 'Chia Seed Water',
    description: 'Chia seeds soaked in water — a fibre-rich drink that prevents glucose spikes.',
    ingredients: [
      'Chia seeds (1 tbsp)',
      'Water (1 glass)',
      'Lemon juice (½)',
      'Cucumber slices (optional)',
    ],
    preparation: 'Stir chia seeds into water. Let soak 10–15 min until gel forms. Add lemon juice and cucumber. Drink slowly.',
    benefits: 'Soluble fibre forms gel in gut, slowing glucose absorption.',
  },
  {
    id: 'DR16',
    name: 'Bitter Melon (Bitter Gourd) Juice',
    description: 'Freshly blended bitter melon juice — one of the most studied anti-diabetic plants.',
    ingredients: [
      'Bitter melon (1 small, from African/Asian store)',
      'Water (½ cup)',
      'Lemon juice',
      'Ginger (optional)',
    ],
    preparation: 'Blend bitter melon with water. Strain through cloth. Add lemon juice. Drink fresh.',
    benefits: 'Contains charantin and polypeptide-p that mimic insulin action.',
  },
  {
    id: 'DR17',
    name: 'Green Tea with Ginger',
    description: 'Classic antioxidant-rich green tea enhanced with fresh ginger.',
    ingredients: [
      'Green tea bag (1)',
      'Ginger (3 slices)',
      'Lemon juice',
      'Hot water (1 cup)',
    ],
    preparation: 'Steep green tea and ginger in hot (not boiling) water 3 min. Remove bag. Add lemon juice.',
    benefits: 'EGCG improves insulin sensitivity, antioxidant-rich.',
  },
  {
    id: 'DR18',
    name: 'Avocado Leaf Tea',
    description: 'Traditional tea made from avocado leaves — used in West Africa to manage blood sugar.',
    ingredients: [
      'Fresh avocado leaves (3–4)',
      'Water (2 cups)',
      'Ginger (optional)',
    ],
    preparation: 'Boil avocado leaves in water 10–15 min. Strain. Cool slightly before drinking.',
    benefits: 'Lowers blood glucose, anti-inflammatory, antioxidant.',
  },
  {
    id: 'DR19',
    name: 'Moringa-Ginger Green Smoothie',
    description: 'Thick green smoothie blending moringa, cucumber, spinach, and ginger — no sugar added.',
    ingredients: [
      'Moringa powder (1 tsp)',
      'Cucumber (½)',
      'Fresh spinach (handful)',
      'Ginger (2 slices)',
      'Lemon juice (1)',
      'Water (1 cup)',
    ],
    preparation: 'Blend all ingredients with water until smooth. Drink immediately.',
    benefits: 'Blood sugar lowering, high in iron, vitamin C, and antioxidants.',
  },
  {
    id: 'DR20',
    name: 'Hibiscus & Ginger Iced Tea',
    description: 'Chilled zobo (hibiscus) tea with fresh ginger — refreshing and blood-sugar friendly.',
    ingredients: [
      'Dried hibiscus flowers (zobo)',
      'Ginger (large chunk)',
      'Cinnamon stick',
      'Cold water (1 litre)',
      'Ice cubes',
      'Lemon',
    ],
    preparation: 'Brew zobo with ginger and cinnamon. Cool, refrigerate, serve over ice with lemon.',
    benefits: 'Lowers blood sugar and blood pressure. Rich in vitamin C.',
  },
];

// ─────────────────────────────────────────────
//  180-DAY SCHEDULE GENERATOR
//  Creates a deterministic schedule using the meal pools above.
// ─────────────────────────────────────────────

/**
 * Build a 180-day meal plan that:
 *  - Cycles through all 30 breakfasts, lunches, and dinners
 *  - Rotates through 20 drinks, pairing different drinks per meal-type
 *  - Ensures no identical meal appears on consecutive days
 */
function generateMealPlan() {
  const plans = [];

  // Drink indices per meal position (breakfast / lunch / dinner)
  // Stagger so each position uses a different drink family
  const drinkOffsets = {
    breakfast: 0,
    lunch: 7,
    dinner: 13,
  };

  for (let day = 1; day <= 180; day++) {
    const idx = day - 1; // zero-based

    // Spread each pool across 180 days (each item repeats 6 times)
    const bIdx = idx % BREAKFASTS.length;
    const lIdx = (idx + 10) % LUNCHES.length;   // offset prevents B + L from same index
    const dIdx = (idx + 20) % DINNERS.length;   // offset prevents clustering

    const bDrinkIdx = (idx + drinkOffsets.breakfast) % DRINKS.length;
    const lDrinkIdx = (idx + drinkOffsets.lunch) % DRINKS.length;
    const dDrinkIdx = (idx + drinkOffsets.dinner) % DRINKS.length;

    plans.push({
      day,
      breakfast: {
        meal: BREAKFASTS[bIdx],
        drink: DRINKS[bDrinkIdx],
      },
      lunch: {
        meal: LUNCHES[lIdx],
        drink: DRINKS[lDrinkIdx],
      },
      dinner: {
        meal: DINNERS[dIdx],
        drink: DRINKS[dDrinkIdx],
      },
    });
  }

  return plans;
}

const MEAL_PLANS = generateMealPlan();

// Helper: return plan for a given day (1-180), cycling for days 181-360
function getPlanForDay(dayNumber) {
  const normalised = ((dayNumber - 1) % 180) + 1;
  return MEAL_PLANS[normalised - 1];
}

// Helper: get today's plan based on calendar day of year
function getTodaysPlan() {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now - start;
  const oneDay = 1000 * 60 * 60 * 24;
  const dayOfYear = Math.floor(diff / oneDay); // 1-365
  return getPlanForDay(dayOfYear);
}
